export interface Product{
    _id: number,
    id:number,
    title: string,
    mrp: number,
    discountPercent: number,
    description: string,
    rating: number,
    seller_id: string,
    brand: string,
    thumbnail: string,
    category: string,
    purchasePrice:number,
    price:number,
}